### ISSUE TITLE
SSL support 

### ISSUE THREAD

**Issue by gempir** [gempir/go-twitch-irc#6]
Currently everything happens over plain TCP but since twitch supports SSL, we should too.

https://dev.twitch.tv/docs/irc#connecting-to-twitch-irc

**Comment by VitorFalcao** [comment]
I would like to work on this. How should this be implemented? Should there be another Connect() function specific for TLS or should I just change the current Connect() function, adding a parameter for specifying the connection type?

**Comment by gempir** [comment]
I'm thinking is there any downside to just using TLS always?

I don't wanna change the API but a second Connect function seems Hacky.

**Comment by VitorFalcao** [comment]
Honestly, I don't see any downside. One could argue about the overhead added by the usage of TLS, but it is negligible. I only see an upside, which is better privacy. I think there are 3 possibilities here, as I see it: Add a parameter to the Connect() function, in order to specify a TLS or non-TLS connection; Create a second Connect() function (tlsConnect?); Ditch plain TCP and use only TLS. The last option doesn't require an API change and improves user's privacy. I would go with the last one. What do you think?

**Comment by gempir** [comment]
Yeah let's go with the last.

**Comment by VitorFalcao** [comment]
Great! I am on it!

**Comment by VitorFalcao** [comment]
@gempir I am almost done, just editing the tests. I noticed that the client_test.go has this piece of code, or at least very similar code, in many tests: https://github.com/gempir/go-twitch-irc/blob/master/client_test.go#L81-L95
How about refactoring that?

**Comment by gempir** [comment]
@VitorFalcao should probably be refactored yeah. The mock almost always behaves very similar.

**Comment by VitorFalcao** [comment]
Ok, I will do it in another pull request
