### ISSUE TITLE
Refactor client tests

### ISSUE THREAD

**Issue by VitorFalcao** [gempir/go-twitch-irc#8]
Many tests share a mock code, for creating the TLS server. Wrap this mock code in another function and then call this function in each test.

**Comment by VitorFalcao** [comment]
I was thinking about creating 2 instances of a client, generate a random number, connect them to the same channel, make one send this random number and the other receive it and check. This would make sure we can connect to the Twitch server, send and receive messages. What do you think? @gempir

**Comment by gempir** [comment]
As a test? Yeah sure

**Comment by VitorFalcao** [comment]
@gempir Decided not to implement the test I mentioned earlier. To send a message to the channel we would need a valid username and oauth key. I was thinking about changing the test `TestCanConnectAndAuthenticate` and make it actually connect to Twitch. What do you think?

**Comment by gempir** [comment]
@VitorFalcao I think before writing system tests, we should improve unit tests. There should be a small server started for unit tests like currently that acts as close to the Twitch servers as possible, with PING, 001 message etc.

This can be done in 1 method like the inital idea of this issue was because all tests rely on this server.
So I think we should do that first and then worry about reading/writing from/to twitch.

**Comment by VitorFalcao** [comment]
I have just finished moving the server mock code to a function and editing the tests as we initially agreed. Could you check this branch: https://github.com/VitorFalcao/go-twitch-irc/tree/refactor-tests ? Should I create a new PR?

**Comment by gempir** [comment]
Yeah create a PR and I'll review it more detailed
