### ISSUE TITLE
JoinMany func

### ISSUE THREAD

**Issue by tensei** [gempir/go-twitch-irc#82]
would be nice to add a .JoinMany(channels ...string) func 
cram as many channels as possible in 512 bytes and send them each to the server

kinda bad calling join on each channel when you have a few hundred channels

**Comment by gempir** [comment]
What exactly are you refering here. Does TMI support some form of joining multiple channels at once? I haven't seen anything like that yet.

**Comment by tensei** [comment]
i pretty sure you can join multiple channels with 
JOIN #channel, #channel ...

**Comment by gempir** [comment]
I haven't seen anything like that, but if that exists it would be useful for sure. So we'll keep this issue around.

**Comment by tensei** [comment]
if you decide to add it, you could just change the .JOIN func parameter to ...string instead string
that wouldn't break existing code... i think

**Comment by gempir** [comment]
Yea. It's useful and non API breaking. I would certainly do it, but we are working on heavy API rewrites in dev first those have priority.

You are free to make a PR yourself though.

**Comment by FletcherCodes** [comment]
From what I can tell, it doesn't exist. I couldn't find anything on Google, and when I tried to do it myself, it'd only join the first channel in the string.

Your best bet would be to have a queue that you loop through once every X seconds, as JOIN is included in your rate limit.

**Comment by tensei** [comment]
ok i tried it with `client.Join("Trainwreckstv,#jakenbakelive")` and it works 
IT'S IMPORTANT TO HAVE NO SPACE BEFORE AND AFTER `,`

**Comment by gempir** [comment]
so I guess we kinda already support it, we should just make the API nicer and limit the 512 bytes, but that's a general thing we should do anyway

**Comment by FletcherCodes** [comment]
Thanks tensei! With that setup, I've managed to get it working for at least 45 channels across 530 characters.

If you'd like to make a PR, that'd be awesome. I say limit the message at 510 characters.

> IRC messages are always lines of characters terminated with a CR-LF
   (Carriage Return - Line Feed) pair, and these messages shall not
   exceed 512 characters in length, counting all characters including
   the trailing CR-LF. Thus, there are 510 characters maximum allowed
   for the command and its parameters.

If the sent parameters exceed that, send the extra channels back as a string slice.

**Comment by brattonross** [comment]
I've implemented a function to create a single irc join message (max 510 characters) from any number of channels, and return any leftover channels as a slice as @IAmFletcher suggested. You can see the code in my commit e8c2f51cff6abbd7859faf4bf1ff06c86b32971c (please excuse my Pepega tests, and feedback is welcome - this is the first time I've written some Go in a while).

I've not yet made any changes to the public api, as I have a question regarding it; @IAmFletcher seems to suggest in the comment above that the Join method should be modified so that it is variadic - is this what should be implemented for this change, or do you want to go with a separate `JoinMany` method?

I also have a few of questions about the code that I have written so far;

1. I don't currently return any errors (e.g. those from `sb.WriteString()`) in order to conform with the api of Join, I'm guessing that this is fine?
2. I currently return `"JOIN"` when either `nil` or no channels are passed to the function - do you think this should be changed at all?
3. I currently return `nil` instead of an empty slice when there are no surplus channels. Would an empty slice be preferable instead? I think an argument could be made either way, although after looking at it I am slightly preferring an empty slice now...

```go
for channelList != nil {
    channelList = client.Join(channelList...)
}
```
vs
```go
for len(channelList) > 0 {
    channelList = client.Join(channelList...)
}
```

**Comment by IAmFletcher** [comment]
Firstly, thank you for tackling this!

My initial vote for modifying the existing Join method is that it doesn't break the API, and would otherwise be code duplication.

1. I just had a look at the implementation of `sb.WriteString()` and it only ever returns a `nil` error.
2. I think it'd be better to return an empty string if channels is equal to `nil`, or empty. That way we can simply do an empty string check in the Join/JoinMany function.
3. Hmm... I want to say return the remainder. That way if you send in a `nil` slice, you'll receive one back. Otherwise, you'll receive an empty slice. I feel doing anything else comes across as an unintended side effect.

If we do want to return a consistent value though, I vote for the empty slice. That way one can continue to utilize the slice after it's returned, and it doesn't break any aliases.

**Comment by IAmFletcher** [comment]
In terms of the tests, I don't see an issue with either of them. There are several possible scenarios, and you use asserts to keep them clean.

One thing I did just notice. is that both are bundled in the irc files. I suggest moving the function in client.go, just underneath the Join/JoinMany function, and the test in the corresponding test file. While I do understand that we are creating an IRC message, irc.go and message.go are both to do with parsing what we get from Twitch to usable structs.

Thanks again!
